FPS = 60
FULL_SCREEN_VIEW = False
WIDTH, HEIGHT = 1600, 900
RECTANGLE_WIDTH_CAP = 650
BACKGROUND = True
RESIZABLE = True
RECT_COMBO_DISPLAY = False
HIDE_PERFECT = False
NUMBER_OF_RECORDS = 4
BACKGROUND_PADDING = 35

DEFAULT_CIRCLE_SIZE = 20
